name: Newman API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -D newman

      - name: Run Postman Collection
        run: npx newman run postman-collection/reqres-api.json --env-var "api_key=${{ secrets.REQRES_API_KEY }}"